name: Granite Lion Cellars
permalink: pretty
collections:
  main-pages:
    output: true
  wines:
    output: true
  avas:
    output: true
  colors:
    output: true
  product-types:
    output: true
  quarterly-shipments: